@startuml
participant SPA
participant "GestaoInfoAPI" as API
participant "PassageController" as Ctrl
participant "PassageService" as Srv
participant "PassageRepo" as Repo
participant "PassageMapper" as Map
participant "PassageDTO" as DTO
participant "Passage" as Domain

activate SPA
SPA -> API: get(/api/passages/:first/:second)
activate API

API -> Ctrl: get
activate Ctrl

Ctrl -> Srv: getPassagesBetweenBuildings()
activate Srv

Srv -> Repo: getPassagesBetweenBuildings()
activate Repo
Repo --> Srv: passages
deactivate Repo

Srv -> Map: converts list of passages to list of passagesDTOs
activate Map
Map --> Srv: passagesDTO
deactivate Map

Srv --> Ctrl: passagesDTO

Ctrl --> API: status code 201
deactivate Ctrl

API --> SPA: success
deactivate API
deactivate SPA
@enduml
