@startuml

actor Actor as Actor
participant "SPA" as Container <<Container (C4)>>
participant "GestaoInfo" as Armazem <<Container (C4)>>

Actor -> Container: Criar passagem entre edifícios
Container --> Actor: Requesita informação para a passagem

Actor -> Container: Envia dados da passagem
Container -> Armazem: POST (/api/passages)

Armazem -> Armazem: Valida edifícios e passagem

alt valida edifícios e passagem

    Armazem -> Armazem: Cria passagem
    Armazem -> Container: Retorna informação da passagem
    Container --> Actor: Retorna informação da passagem
else edifícios ou passagem inválidos
    Armazem -> Container: Retorna erro
    Container --> Actor: Retorna erro
end

@enduml
