@startuml

actor Actor as Actor
participant "SPA" as Container <<Container (C4)>>
participant "GestaoInfo" as Armazem <<Container (C4)>>

Actor -> Container: Criar novo robo
Container --> Actor: Requesita dados do novo robo

Actor -> Container: Envia dados do novo robo
Container -> Armazem: POST(/api/robots)

alt sucesso na criação
    Armazem --> Container: Retorna sucesso na criação
    Container --> Actor: Retorna sucesso na criação
else falha na criação
    Armazem --> Container: Retorna falha na criação
    Container --> Actor: Retorna falha na criação
end

@enduml
