@startuml

actor "Gestor de campus" as Actor
participant "SPA" as Container <<Container (C4)>>
participant "GestaoInfoAPI" as API <<Container (C4)>>

Actor -> Container:  editar edifícios
Container --> Actor: requesita os dados do edifício
Actor --> Container: edita os dados do edifício
Container -> API: put(/api/buildings)

API --> Container: status code
alt 200
    Container --> Actor: devolve o edifício editado
else 400
    Container --> Actor: devolve mensagem de erro
end

@enduml
