@startuml
participant SPA
participant "GestaoInfoAPI" as API
participant "BuildingController" as Ctrl
participant "BuildingService" as Srv
participant "BuildingRepo" as Repo
participant "BuildingMapper" as Map
participant "BuildingDTO" as DTO
participant "Building" as Domain

activate SPA
SPA -> API: get(/api/buildings/min/:id/max/:id)
activate API

API -> Ctrl: get
activate Ctrl

Ctrl -> Srv: getBuildingsByFloorRange()
activate Srv

Srv -> Repo: getBuildingsByFloorRange()
activate Repo
Repo --> Srv: buildings
deactivate Repo

Srv -> Map: converts list of buildings to list of buildingDTOs
activate Map
Map --> Srv: buildingsDTO
deactivate Map

Srv --> Ctrl: buildingsDTO

Ctrl --> API: status code 201
deactivate Ctrl

API --> SPA: success
deactivate API
deactivate SPA
@enduml
