@startuml
participant SPA
participant "GestaoInfoAPI" as API
participant "RobotTypeController" as Ctrl
participant "RobotTypeService" as Srv
participant "RobotTypeRepo" as Repo
participant "RobotTypeMapper" as Map
participant "RobotTypeDTO" as DTO
participant "RobotType" as Domain

activate SPA
SPA -> API: post(/api/robotTypes)
activate API

API -> Ctrl: post
activate Ctrl

Ctrl -> Srv: createRobotType(robotTypeDTO)
activate Srv

Srv -> Domain: create

Srv -> Repo: save(robotType)
activate Repo
Repo --> Srv: robotType
deactivate Repo

Srv -> Map: toDTO(robotType)
activate Map
Map --> Srv: robotTypeDTO
deactivate Map

Srv --> Ctrl: robotTypeDTO

Ctrl --> API: status code 201
deactivate Ctrl

API --> SPA: success
deactivate API
deactivate SPA
@enduml
