@startuml
participant SPA
participant "GestaoInfoAPI" as API
participant "BuildingController" as Ctrl
participant "BuildingService" as Srv
participant "BuildingRepo" as Repo
participant "BuildingMapper" as Map
participant "BuildingDTO" as DTO
participant "Building" as Domain

activate SPA
SPA -> API: put(/api/buildings)
activate API

API -> Ctrl: put
activate Ctrl

Ctrl -> Srv: updateBuilding(buildingDTO)
activate Srv

' create Domain
' Srv -> Domain: create
Srv -> Repo: findByDomainId(buildingId)
activate Repo
Repo --> Srv: building
Srv -> Srv: updates building info
Srv -> Repo: save(building)
Repo --> Srv: building
deactivate Repo

Srv -> Map: toDTO(building)
activate Map
Map --> Srv: buildingDTO
deactivate Map

Srv --> Ctrl: buildingDTO

Ctrl --> API: status code 201
deactivate Ctrl

API --> SPA: success
deactivate API
deactivate SPA
@enduml