@startuml

actor Actor as Actor
participant "robDroneGo:robDroneGo" as Container <<Container (C4)>>

Actor -> Container: Pretende listar pisos de edifícios com passagens para outros edifícios

Container -> Container: Requisita pisos com passagens

alt sucesso na requisição
    Container --> Actor: Devolve pisos com passagens
else falha na requisição
    Container --> Actor: Devolve mensagem de erro
end

@enduml
