@startuml

actor "Admin" as Actor
participant "robDroneGo:robDroneGo" as Container <<Container (C4)>>

Actor -> Container: requisita a criação de um novo utilizador
Container --> Actor: requisita os dados do utilizador e as suas permissoes
Actor -> Container: envia os dados do utilizador e as suas permissoes

alt sucesso
    Container --> Actor: retorna mensagem de sucesso
else falha
    Container --> Actor: devolve mensagem de erro
end


@enduml
