@startuml

actor "Utente" as Actor
participant "robDroneGo:robDroneGo" as Container <<Container (C4)>>

Actor -> Container: requisita a eliminação da conta de utilizador

alt sucesso
    Container --> Actor: retorna mensagem de sucesso
else falha
    Container --> Actor: devolve mensagem de erro
end


@enduml
