@startuml
participant SPA
participant "MPT API" as API
participant "TaskController" as Ctrl
participant "TaskService" as Srv
participant "MGI API" as API2

participant "TaskRepo" as Repo
participant "UserRepo" as ur
participant "TaskMapper" as Map
participant "UserMapper" as um
participant "SurveillanceTask" as SurveillanceTask
participant "PickupDeliveryTask" as PickupDeliveryTask

activate SPA


SPA -> API: PATCH(/api/tasks/)
activate API
API -> API: auth middleware 

API -> Ctrl: PATCH
activate Ctrl
Ctrl -> Ctrl: permissions middleware 

Ctrl -> Srv: ApproveReject
activate Srv
Srv -> Repo: update aprove/reject field

activate Repo
Repo --> Map: toDto
activate Map
Map -> Repo: TaskDto
deactivate Map
Repo --> Srv: TaskDto
deactivate Repo

    
Srv --> Ctrl: taskDto
deactivate Srv

Ctrl --> API: status code 200

deactivate Ctrl
deactivate API

API --> SPA: success

deactivate API







@enduml