@startuml
participant SPA
participant "MPT API" as API
participant "UserController" as Ctrl
participant "UserService" as Srv
participant "UserRepo" as Repo
participant "UserMapper" as Map
participant "RoleRepo" as rr
participant "RoleMapper" as rm



SPA -> API: PATCH(/api/users/)
activate API

API -> API: auth middleware

API -> Ctrl: UpdateMyProfile(user)
activate Ctrl
Ctrl -> Ctrl: permissions middleware

Ctrl -> Ctrl: get current user from

Ctrl -> Srv: UpdateMyProfileAsync(user, currentUser.Id)
activate Srv

Srv -> Srv: GetByIdAsync(id)

Srv -> Srv: check if user is valid (exists, active, approved)
Srv -> Srv: update user fields

Srv -> Repo: CommitAsync(user)
Srv -> Map: ToProfileDto(user)
activate Map
Map --> Srv: userDto
deactivate Map

Srv --> Ctrl: userDto
deactivate Srv

Ctrl --> API: userDto
deactivate Ctrl

API --> SPA: userDto
deactivate API








@enduml