@startuml
participant SPA
participant "MPT API" as API
participant "UserController" as Ctrl
participant "UserService" as Srv
participant "UserRepo" as Repo
participant "UserMapper" as Map
participant "Email" as Email
participant "RoleRepo" as rr
participant "RoleMapper" as rm

activate SPA
SPA -> API: POST(/api/auth/signup)
activate API


API -> Ctrl: AddAsync(user)
activate Ctrl

Ctrl -> Srv: AddAsync(user)
activate Srv

Srv -> Srv: check if email is already in use

Srv -> Srv: hash password

Srv -> Map: toDomain(user)
activate Map
Map --> Srv: User
deactivate Map

Srv -> Repo: AddAsync(user)
activate Repo
Repo -> Repo: AddAsync(user)
Repo --> Srv: User
deactivate Repo

Srv -> Map: toDTO(User)
activate Map
Map --> Srv: UserDTO
deactivate Map

Srv --> Ctrl: UserDTO
deactivate Srv

Ctrl --> API: status code 201
deactivate Ctrl

API --> SPA: success
deactivate API



@enduml