@startuml
participant SPA
participant "MPT API" as API
participant "UserController" as Ctrl
participant "UserService" as Srv
participant "UserRepo" as Repo
participant "UserMapper" as Map
participant "RoleRepo" as rr
participant "RoleMapper" as rm

activate SPA
SPA -> API: PUT(/api/users/)
activate API

API -> API: auth middleware 

API -> Ctrl: ApproveReject(id, user)
activate Ctrl
Ctrl -> Ctrl: permissions middleware 

Ctrl -> Srv: UpdateIsApprovedAsync(id, user)
activate Srv

Srv -> Srv: GetByIdAsync(id)
Srv -> Srv: change user state to approved or rejected

Srv -> Repo: CommitAsync(user)
Srv -> Map: toDTO(user)
activate Map
Map --> Srv: UserDto
deactivate Map

Srv --> Ctrl: UserDto
deactivate Srv

Ctrl --> API: status code 200
deactivate Ctrl

API --> SPA: success
deactivate API






@enduml