@startuml
participant SPA
participant "MPT API" as API
participant "UserController" as Ctrl
participant "UserService" as Srv
participant "UserRepo" as Repo
participant "UserMapper" as Map


activate SPA
SPA -> API: DELETE(/api/users/profile)
activate API

API -> API: auth middleware
API -> Ctrl: DeleteMyProfile()
activate Ctrl

Ctrl -> Ctrl: permissions middleware
Ctrl -> Ctrl: get current user
Ctrl -> Srv: DeleteIgnoringActiveAsync(userId)
activate Srv

Srv -> Repo: user = GetByIdAsync(id)
activate Repo

Srv -> Repo: Remove(user)
Srv -> Srv: CommitAsync()
deactivate Repo

Srv -> Map: Map(user)
activate Map
Map -> Srv: userDto
deactivate Map

Srv -> Ctrl: return userDto
deactivate Srv
Ctrl -> API: return 200
deactivate Ctrl
API -> SPA: success
deactivate API


@enduml