@startuml
participant SPA
participant "GestaoInfoAPI" as API
participant "RobotController" as Ctrl
participant "RobotService" as Srv
participant "RobotRepo" as Repo
participant "RobotTypeRepo" as Repo2
participant "RobotMapper" as Map
participant "RobotDTO" as DTO
participant "Robot" as Domain

activate SPA
SPA -> API: post(/api/robots)
activate API

API -> Ctrl: post
activate Ctrl

Ctrl -> Srv: createRobot(robotDTO)
activate Srv

Srv -> Repo2: findByDomainId(robot.robotTypeId)
activate Repo2
Repo2 --> Srv: robotType
deactivate Repo2

Srv -> Domain: create
Srv -> Repo: save(robot)
activate Repo
Repo --> Srv: robot
deactivate Repo

Srv -> Map: toDTO(robot)
activate Map
Map --> Srv: robotDTO
deactivate Map

Srv --> Ctrl: robotDTO

Ctrl --> API: status code 201
deactivate Ctrl

API --> SPA: success
deactivate API
deactivate SPA
@enduml
