@startuml

actor Actor as Actor
participant "robDroneGo:robDroneGo" as Container <<Container (C4)>>

Actor -> Container: Pretende editar as informações de uma passagem

Container --> Actor: Mostra informações atuais da passagem

Actor -> Container: Envia dados atualizados

Container -> Container: Atualiza dados da passagem

alt sucesso na edição
    Container --> Actor: Devolve a passagem editada
else falha na edição
    Container -> Actor: Mostra mensagem de erro
end
@enduml
