@startuml

actor GestorFrota as User

participant SPA
participant "GestaoInfoAPI" as API

User -> SPA: requisita página dos tipos de robo
SPA -> User: retorna página dos tipos de robo

User -> SPA: seleciona opção de adicionar tipo de robo
SPA -> User: mostra formulário de adicionar tipo de robo

SPA -> API: get(/api/tastTypes)
API --> SPA: mostra tipos de tarefas na select box

User -> SPA: preenche formulário e submete

SPA -> API: post(/api/robotTypes)

note right of API 
    Restantes passos representados no 
    diagrama da API disponivel na pasta API
end note

API --> SPA: successo
SPA --> User: retorna sucesso

@enduml