@startuml

actor Actor as Actor
participant "SPA" as Container <<Container (C4)>>
participant "GestaoInfoAPI" as API <<Container (C4)>>

Actor -> Container:  listar todos os edifícios
Container -> API: get(/api/buildings)

API --> Container: status code
alt 200
    Container --> Actor: devolve todos os edifícios
else 400 
    Container --> Actor: devolve mensagem de erro
end

@enduml
