@startuml

actor "Utente" as Actor
participant "SPA" as Container <<Container (C4)>>
participant "MPT API" as API <<Container (C4)>>

Actor -> Container: requisitar uma tarefa
Container --> Actor: requisita o ponto inicial e final da tarefa
Actor -> Container: insere os dados para criação da tarefa

alt task surveillance
    Container -> API: POST(/api/tasks/surveillance)
else task pickupdelivery
    Container -> API: POST(/api/tasks/pickupdelivery)
end


API --> Container: status code
alt sucesso na criação da tarefa
    Container --> Actor: devolve mensagem de sucesso
else falha na criação da tarefa
    Container --> Actor: devolve mensagem de erro
end

@enduml
