@startuml

actor "Utente" as Actor
participant "SPA" as Container <<Container (C4)>>
participant "MPT API" as API <<Container (C4)>>

Actor -> Container: requisita uma cópia dos dados do utilizador

Container -> API: GET(/api/users/allInfo)

alt sucesso
    API --> Container: retorna um ficheiro .json com os dados
    Container --> Actor: retorna um ficheiro .json e faz o seu download
else falha
    API --> Container: retorna um erro
    Container --> Actor: devolve mensagem de erro
end

@enduml
