@startuml

actor "Utente" as Actor
participant "SPA" as Container <<Container (C4)>>
participant "MPT API" as API <<Container (C4)>>

Actor -> Container: requisita a eliminação da conta de utilizador

Container -> API: DELETE(/api/users/:id)

alt sucesso
    API --> Container: retorna mensagem de sucesso
    Container --> Actor: retorna mensagem de sucesso
else falha
    API --> Container: retorna mensagem de erro
    Container --> Actor: devolve mensagem de erro
end

@enduml
