@startuml

actor Actor as Actor
participant "robDroneGo:robDroneGo" as Container <<Container (C4)>>

Actor -> Container: Pretende listar edifícios com mínimo e máximo de andares
Container --> Actor: Requisita mínimo e máximo de andares

Container -> Container: Requisita edifícios com mínimo e máximo de andares

alt sucesso na requisição
    Container --> Actor: Devolve edifícios com mínimo e máximo de andares
else falha na requisição
    Container --> Actor: Devolve mensagem de erro
end

@enduml
