@startuml

actor Actor as Actor
participant "robDroneGo:robDroneGo" as Container <<Container (C4)>>

Actor -> Container: Pretende editar as informações de um edifício
Container --> Actor: Mostra informações atuais do edifício

Actor -> Container: Envia dados atualizados
Container -> Container: Atualiza dados do edifício

alt sucesso case
    Container --> Actor: Mostra mensagem de sucesso
else erro case
    Container -> Container: Mostra mensagem de erro
end
@enduml
