@startuml

actor Actor as Actor
participant "robDroneGo:robDroneGo" as Container <<Container (C4)>>

Actor -> Container: Criar passagem entre edifícios
Container --> Actor: Requesita informação para a passagem

Actor -> Container: Envia dados da passagem
Container -> Container: Valida edifícios e passagem
Container --> Container: Cria passagem

alt valida edifícios e passagem

    Container --> Actor: Retorna informação da passagem
else edifícios ou passagem inválidos
    Container --> Actor: Retorna erro
end


@enduml
