@startuml

actor "Gestor de campus" as Actor
participant "robDroneGo:robDroneGo" as Container <<Container (C4)>>

Actor -> Container: criar um novo edifício
Container --> Actor: requesita os dados do edifício
Actor -> Container: insere os dados do edifício

alt sucesso na a criar o edifício
    Container --> Actor: devolve o edifício criado
else falha na requisição
    Container --> Actor: devolve mensagem de erro
end

@enduml
