@startuml

actor "Gestor de campus" as Actor
participant "robDroneGo:robDroneGo" as Container <<Container (C4)>>

Actor -> Container: criar piso de edifício
Container --> Actor: requesita os dados do piso
Actor -> Container: insere os dados do piso

alt sucesso na a criar o piso
    Container --> Actor: devolve o piso cirado
else falha na requisição
    Container --> Actor: devolve mensagem de erro
end


@enduml
