@startuml component
skinparam DefaultFontName Arial
skinparam DefaultFontSize 16
skinparam DefaultFontStyle bold
skinparam ArrowThickness 2.5
!theme toy

title components diagram

' modulos
[Módulo\nGestão de informação] as gi
[Módulo\nPlaneamento] as p
[Módulo\nVisualização 3D] as v3d

' interfaces
interface "MGI API" as giApi

' conexoes
giApi - gi
p -( giApi
v3d -( giApi

@enduml
