@startuml domain model
skinparam DefaultFontName Arial
skinparam DefaultFontSize 16
skinparam DefaultFontStyle bold
skinparam ArrowThickness 2.5
!theme toy

title domain model

package "<<aggregate>> Building"{

    entity Building <<entity>><<root>>{
        code
        name
        dimensions
    }

}

package "<<aggregate>> Elevator"{

    entity Elevator <<entity>><<root>>{
        designation
        floorsAllowed
    }

}

package "<<aggregate>> Floor"{
    entity Floor <<entity>>{
        number
        information
    }
}

package "<<aggregate>> FloorMap"{
    entity FloorMap <<entity>>{
        map
        doors
    }
}

package "<<aggregate>> Room"{
    entity Room <<entity>>{
        number
    }
}

package "<<aggregate>> Passage"{
    entity Passage <<entity>>{
        designation
    }
}


package "<<aggregate>> User"{
    entity User <<entity>><<root>>{
        firstName
        lastName
        email
        password
        role
    }
}

package "<<aggregate>> Robot"{
    entity Robot <<entity>><<root>>{
        identification
        nickname
        serialNumber
        description
        state
    }
}

package "<<aggregate>> RobotType"{
    entity RobotType <<entity>><<root>>{
        type
        brand
        model
        tasksAllowed
    }
}

package "<<aggregate>> Role"{
    entity Role <<entity>><<root>>{
        name
    }
}

' package "<<aggregate>> Drone"{

'     entity Drone <<entity>><<root>>{

'     }

' }

package "<<aggregate>> Task"{
    entity Task <<entity>><<root>>{
        designation
    }
}

package "<<aggregate>> TaskType"{
    entity TaskType <<entity>><<root>>{
        name
        designation
    }
}

' connections
'user
User "*" --- "1" Role: has >

' building
Floor "*" --- "1" Building: is associated >
Elevator "1" --- "1" Building: is associated >

' floor
Room "*" --- "1" Floor: is on >

'passage
Passage "*" --- "1" Floor: connects >

' task
Task "*" --- "1" Robot: is associated >
Task "*" --- "1" TaskType: has a >

' robot
Robot "*" --- "1" RobotType: has a >

' robotType
RobotType "*" --- "*" TaskType: is allowed >

' floorMap
FloorMap "*" --- "1" Floor: is associated >
FloorMap "*" --- "*" Passage: has associated>
FloorMap "*" --- "*" Room: has associated >
FloorMap "*" --- "1" Elevator: has associated >

' 



@enduml


