@startuml

actor Actor as Actor
participant "SPA" as Container <<Container (C4)>>
participant "API" as API <<Container (C4)>>

Actor -> Container: Pretende listar edifícios com mínimo e máximo de andares
Container --> Actor: Requisita mínimo e máximo de andares

    Container -> API: get(/api/buildings?min=MIN&max=MAX)

alt sucesso na requisição
    API --> Container: Devolve edifícios com mínimo e máximo de andares
    Container --> Actor: Devolve edifícios com mínimo e máximo de andares
else falha na requisição
    API --> Container: Devolve mensagem de erro
    Container --> Actor: Devolve mensagem de erro
end

@enduml
