@startuml

actor Actor as Actor
participant "SPA" as Container <<Container (C4)>>
participant "API" as API <<Container (C4)>>

Actor -> Container: Pretende listar passagens entre dois edifícios

Container --> Actor: Requisita o codigo de cada edifício

Container -> API: get(/api/passages/:first/:second)

alt 200
    API --> Container: Devolve as passagens entre os edifícios
    Container --> Actor: Devolve as passagens entre os edifícios
else 400
    API --> Container: Devolve mensagem de erro
    Container --> Actor: Devolve mensagem de erro
end

@enduml
