name: Deploy to DEI VM

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      - name: Install dependencies
        
        run: |
          cd spa
          npm install

      - name: Build Angular application
        run: |
          cd spa
          npm run build
        

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: vsgate-ssh.dei.isep.ipp.pt
          port: 10597
          username: root
          password: root.
          source: spa/dist/
          target: /var/www/html

      - name: SSH into server and restart web server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: vsgate-ssh.dei.isep.ipp.pt
          port: 10597
          username: root
          password: root.
          script: |
            sudo systemctl restart apache2 
