name: Deploy and Execute Commands

on:
  push:
    branches:
      - main

jobs:
  deploy_and_execute:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.18.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.2
      with:
        key: ${{secrets.SSH_PRIVATE_KEY}}
        host: ${{secrets.VM_IP}}
        username: ${{secrets.VM_USERNAME}}
        script: |
          pm2 delete all
          cd /home/ubuntu/API
          rm -rf mgi

