name: Deploy and Execute Commands

on:
  push:
    branches:
      - main

jobs:
  deploy_and_execute:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.18.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.2
      with:
        key: ${{secrets.SSH_PRIVATE_KEY}}
        host: ${{secrets.VM_IP}}
        port: 10655
        username: ${{secrets.VM_USERNAME}}
        script: |
          pm2 delete all
          # ./killAPI.sh
          cd /home/ubuntu/API
          rm -rf repo
          git clone --depth 1 --filter=blob:none --no-checkout https://ruben1132:${{secrets.PAT_TOKEN}}@github.com/ruben1132/PI5_23-24.git repo
          cd repo
          git sparse-checkout init --cone
          git sparse-checkout set mgi
          git pull
          cd mgi
          npm install
          nohup npm run start &
