name: Deploy and Execute Commands

on:
  push:
    branches:
      - main

jobs:
  deploy_and_execute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2



      - name: Execute SSH Commands
        run: |
          # Replace these variables with your SSH and server details
          SERVER_IP="vsgate-ssh.dei.isep.ipp.pt"
          SSH_PORT="10655"  # Replace with your desired SSH port
          SSH_USERNAME="root"
          SSH_PRIVATE_KEY="${{ secrets.SSH_PRIVATE_KEY }}"
      
          # Save SSH private key to a file and set permissions
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
      
          # Accept the SSH host key and add it to the known hosts file
          ssh-keyscan -p $SSH_PORT "$SERVER_IP" >> .github/workflows/known_hosts
      
          # SSH into the server and execute commands
          ssh -i ssh_key -p $SSH_PORT "$SSH_USERNAME@$SERVER_IP" "sudo npm i && sudo npm start"
      
          # Cleanup (remove the private key)
          rm ssh_key
  
